name: Continuous Delivery

on:
  push:
    branches:
      - main # ou qualquer outra branch

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: pokedex-projeto-zipado.zip
          path: |
            index.html
            README.md
            public/pokeball.svg'
            src/main.jsx
            src/App.jsx
            src/pages/Home.jsx
            src/components/Navbar/index.jsx
            src/components/PokemonCard/index.jsx'
            src/images/cards/who_is_that_pokemon.png
