name: Continuous Delivery

on:
  push:
    branches:
      - main # ou qualquer outra branch

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: pokedex-projeto-zipado
          path: |
            index.html
            README.md
            public/pokeball.svg'
            **.jsx
            src/images/cards/who_is_that_pokemon.png

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pokedex-projeto-zipado
      - name: Display structure of downloaded files
        run: ls -R
